### PR TITLE
Junit replace invalid characters

### LINKED ISSUE #615: Junit reporter breaks with new error messages of elm-program-test
The new test output of elm-program-test breaks the junit output of elm-test.
 
# Error
```
└─ elm-test  --report junit
/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLStringifier.js:210
            throw new Error(`Invalid character in string: ${str} at index ${res.index}`);
            ^

Error: Invalid character in string: ▼ Query.fromHtml

    &lt;input id="id"&gt;&lt;/input&gt;


▼ ProgramTest.fillIn ""

Expected one of the following to exist and have an "oninput" handler:
- &lt;input&gt; with aria-label and id
    ✓ has tag "input"
    ✓ has attribute "id" "id"
    ✗ has attribute "aria-label" ""
- &lt;textarea&gt; with aria-label and id
    ✗ has tag "textarea" at index undefined
    at XMLStringifier.assertLegalChar (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLStringifier.js:210:19)
    at XMLStringifier.text (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLStringifier.js:53:21)
    at new XMLText (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLText.js:22:37)
    at XMLElement.text (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:308:17)
    at XMLElement.node (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:294:17)
    at XMLElement.element (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:187:30)
    at XMLElement.element (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:163:32)
    at XMLElement.element (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:158:27)
    at XMLElement.element (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:148:34)
    at XMLDocument.element (/nix/store/yyi707rsplzcqw9917swgkk70ckl69jy-elm-test-0.19.1-revision7/lib/node_modules/elm-test/node_modules/xmlbuilder/lib/XMLNode.js:158:27)
```

# Reproduce

```elm
module Example exposing (..)

import Html
import Html.Attributes exposing (id)
import ProgramTest exposing (ProgramTest)
import Test exposing (..)
import Test.Html.Selector exposing (text)


start : ProgramTest () msg (Cmd msg)
start =
    ProgramTest.createElement
        { init = \_ -> ( (), Cmd.none )
        , view = \_ -> Html.input [ id "id" ] []
        , update = \_ _ -> ( (), Cmd.none )
        }
        |> ProgramTest.start ()


tests : Test
tests =
    test "Hello World"
        (\() ->
            start
                |> ProgramTest.fillIn "id" "" "Hello World"
                |> ProgramTest.expectViewHas [ text "Hello World" ]
        )
```

Run: `elm-test --report junit`

# Potential Fix

We could include a `invalidCharReplacement` option as per https://github.com/oozcitak/xmlbuilder-js/issues/147#issuecomment-604375441

### PR DESCRIPTION
**Pull request by zwilias**
Fixes #615

### CODE REVIEW

File: lib/Supervisor.js [hunk 1]
```diff
@@ -201,7 +201,23 @@ function run(
...
                 xml.testsuite.testcase = xml.testsuite.testcase.concat(values);
 
-                console.log(XmlBuilder.create(xml).end());
+                // The XmlBuilder by default does not remove characters that are
+                // invalid in XML, like backspaces. However, we can pass it an
+                // `invalidCharReplacement` option to tell it how to handle
+                // those characters, rather than crashing. In an attempt to
+                // retain useful information in the output, we try and output a
+                // hex-encoded unicode codepoint for the invalid character. For
+                // example, a backspace (`\u{08}` in Elm) will be output as
```
Comment (lydell) [inline lib/Supervisor.js:210]:
```suggestion
                // example, a backspace (`\u{0008}` in Elm) will be output as
```

**Review by lydell — COMMENTED** [review]
Would be nice with a test case from https://github.com/rtfeldman/node-test-runner/issues/615 (making sure that the new test output of elm-program-test works).

File: lib/Supervisor.js [hunk 2]
```diff
@@ -201,7 +201,23 @@ function run(
...
+                // `\0x8`.
```
Comment (lydell) [inline lib/Supervisor.js:211]: Is this format used in any language? If not, is there a reason to invent a new syntax rather than using some already existing one?

File: lib/Supervisor.js (hunk 1 above)
Comment (zwilias) [reply lib/Supervisor.js]: Resolved in https://github.com/rtfeldman/node-test-runner/pull/625/commits/41e357c03a66b2ee872d5931d0c5640139a6b3aa

**Comment by zwilias** [comment]
> Would be nice with a test case from https://github.com/rtfeldman/node-test-runner/issues/615

Yeah, I'm a little hesitant about having `node-test-runner`'s test-suite depend on some version of `elm-program-test`. Given the core-issue is that it outputs control characters, and we can test that control characters are handled, I don't feel like there's a particular need for adding an external dependency to the test suite.

That said, I can confirm it resolves the issue and results in actual XML output 😄

**Comment by lydell** [comment]
Oh, I thought it was the “▼” character that caused the problem … so elm-program-test uses `\u{0008}`? If it does, then the tests are all good. I didn’t mean that we should depend on elm-program-test.

Now I’m curious, why does it use control characters? (Just out of curiosity, not trying to question the need for this PR.)

**Comment by zwilias** [comment]
It uses a bunch of control characters for formatting text in the output (bold, red, green, dim, etc). This mostly means `\u{001B}`, though we'd want the test-runner to work with any character that's somewhat legal to have in a string 😄

**Comment by lydell** [comment]
I think `\u{001B}` would make for a much better test case. I immediately think of terminal escapes when I see it.

**Comment by zwilias** [comment]
Cool, I went ahead and added an extra test-case. I like having both, so as to not overfit to how it happened to be elm-program-test that surfaced the issue, while also having the clarity of something a little easier to image appearing in test output!

File: lib/Supervisor.js [hunk 3]
```diff
@@ -201,7 +201,27 @@ function run(
...
 
-                console.log(XmlBuilder.create(xml).end());
+                // The XmlBuilder by default does not remove characters that are
+                // invalid in XML, like backspaces. However, we can pass it an
+                // `invalidCharReplacement` option to tell it how to handle
+                // those characters, rather than crashing. In an attempt to
+                // retain useful information in the output, we try and output a
+                // hex-encoded unicode codepoint for the invalid character. For
+                // example, a backspace (`\u{0008}` in Elm) will be output as a
+                // literal `\u{0008}`.
```
Comment (lydell) [inline lib/Supervisor.js:211]:
```suggestion
                // example, the start of a terminal escape (`\u{001B}` in Elm) will be output as a
                // literal `\u{001B}`.
```

File: tests/ci.js [hunk 4]
```diff
@@ -292,6 +292,12 @@ describe('Testing elm-test on single Elm files', () => {
     }
   }
 
+  it(`Should not crash the junit reportor on invalid characters`, () => {
```
Comment (lydell) [inline tests/ci.js:295]:
```suggestion
  it(`Should not crash the junit reporter on invalid characters`, () => {
```

**Review by lydell — APPROVED** [review]
Looks good to me!

@harrysarson do you have anything to say?

**Comment by zwilias** [comment]
I'm going to go ahead and merge this, we can always make fixups later.

**Comment by lydell** [comment]
Released in 0.19.1-revision12.
